A/A/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/',include('administration.urls',namespace='administration')),
    path('', include('core.urls',namespace='core')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A/administration/urls.py
from django.urls import path
from . import views
from django.urls import re_path
from . import consumers

app_name = 'administration'

urlpatterns = [
    path('',views.Index.as_view(),name="index"),    
    # ====================================
    path('user-management/',views.UserManagement.as_view(),name="user-management"),    
    path('edit-user/<str:user_id>',views.EditUser.as_view(),name="edit-user"),    
    path('block-user/<str:user_id>',views.BlockUser.as_view(),name="block-user"),    
    path('user-actions/<str:user_id>',views.UserActions.as_view(),name="user-actions"),
    path('user-appointments/<str:user_id>',views.UserAppointments.as_view(),name="user-appointments"),
    path('doctor-appointments/<str:user_id>',views.DoctorAppointments.as_view(),name="doctor-appointments"),
    path('add-user-appointment/<str:user_id>',views.AddUserAppointment.as_view(),name="add-user-appointment"),
    path('edit-user-appointment/<str:appointment_id>',views.EditUserAppointment.as_view(),name="edit-user-appointment"),
    path('edit-doctor-appointment/<str:appointment_id>',views.EditDoctorAppointment.as_view(),name="edit-doctor-appointment"),
    # ====================================
    path('role-management/',views.RoleManagement.as_view(),name="role-management"),    
    path('add-role/',views.AddRole.as_view(),name="add-role"),    
    path('edit-role/<str:role_id>',views.EditRole.as_view(),name="edit-role"),    
    path('remove-role/<str:role_id>',views.RemoveRole.as_view(),name="remove-role"),    
    # ====================================
    path('category-management/',views.CategoryManagement.as_view(),name="category-management"),    
    path('add-category/',views.AddCategory.as_view(),name="add-category"),    
    path('edit-category/<str:category_id>',views.EditCategory.as_view(),name="edit-category"),    
    path('remove-category/<str:category_id>',views.RemoveCategory.as_view(),name="remove-category"),    
    path('add-sub-category/<str:category_id>',views.AddSubCategory.as_view(),name="add-sub-category"),    
    path('edit-sub-category/<str:sub_category_id>',views.EditSubCategory.as_view(),name="edit-sub-category"),    
    path('remove-sub-category/<str:sub_category_id>',views.RemoveSubCategory.as_view(),name="remove-sub-category"),    
    # ====================================
    path('picture-management/',views.PictureManagement.as_view(),name="picture-management"),    
    path('add-picture/',views.AddPicture.as_view(),name="add-picture"),    
    path('edit-picture/<str:picture_id>',views.EditPicture.as_view(),name="edit-picture"),    
    path('remove-picture/<str:picture_id>',views.RemovePicture.as_view(),name="remove-picture"),    
    # ====================================
    path('edit-site-settings/',views.EditSiteSettings.as_view(),name="edit-site-settings"),    
    # ====================================
    path('sms-logs/',views.SmsLogs.as_view(),name="sms-logs"),    
    # ====================================
    path('blocked-ips/',views.IpManagement.as_view(),name="ip-management"),    
    path('add-blocked-ip/',views.AddBlockedIp.as_view(),name="add-blocked-ip"),    
    path('remove-blocked-ip/<str:id>',views.RemoveBlockedIp.as_view(),name="remove-blocked-ip"),    
    # ====================================
]

# websocket_urlpatterns = [
#         path('ws/logs/sms-logs/', consumers.DataConsumer.as_asgi()),
# ]

A/administration/forms.py
from .administration_forms.editUser import EditUserForm
from .administration_forms.addRole import AddRoleForm
from .administration_forms.addPicture import AddPictureForm
from .administration_forms.addCategory import AddCategoryForm
from .administration_forms.addSubCategory import AddSubCategoryForm
from .administration_forms.siteSettings import SiteSettingsForm
from .administration_forms.addUserAppointment import AddUserAppointmentForm
from .administration_forms.addBlockedIp import AddBlockedIpForm

A/administration/views.py
from .pages.index import Index
# ========================================================
from .pages.UserManagement.userManagement import UserManagement
from .pages.UserManagement.blockUser import BlockUser
from .pages.UserManagement.editUser import EditUser
from .pages.UserManagement.userActions import UserActions
from .pages.UserManagement.userAppointments import UserAppointments
from .pages.UserManagement.doctorAppointments import DoctorAppointments
from .pages.UserManagement.addUserAppointment import AddUserAppointment
from .pages.UserManagement.editUserAppointment import EditUserAppointment
from .pages.UserManagement.editDoctorAppointment import EditDoctorAppointment
# ========================================================
from .pages.RoleManagement.roleManagement import RoleManagement
from .pages.RoleManagement.add_role import AddRole
from .pages.RoleManagement.edit_role import EditRole
from .pages.RoleManagement.remove_role import RemoveRole
# ========================================================
from .pages.CategoryManagement.categoryManagement import CategoryManagement
from .pages.CategoryManagement.add_category import AddCategory
from .pages.CategoryManagement.edit_category import EditCategory
from .pages.CategoryManagement.remove_category import RemoveCategory
from .pages.CategoryManagement.add_sub_category import AddSubCategory
from .pages.CategoryManagement.edit_sub_category import EditSubCategory
from .pages.CategoryManagement.remove_sub_category import RemoveSubCategory
# ========================================================
from .pages.PictureManagement.pictureManagement import PictureManagement
from .pages.PictureManagement.add_picture import AddPicture
from .pages.PictureManagement.edit_picture import EditPicture
from .pages.PictureManagement.remove_picture import RemovePicture
# ========================================================
from .pages.SiteSettings.edit_site_settings import EditSiteSettings
# ========================================================
from .pages.Logs.smsLogs import SmsLogs
# ========================================================
from .pages.Common.blocked_ips import IpManagement
from .pages.Common.add_blocked_ip import AddBlockedIp
from .pages.Common.remove_blocked_ip import RemoveBlockedIp
# ========================================================

A/administration/templates/doctor-appointments/doctor-appointments.html
{% extends 'layouts/administration/administration_base.html' %}
{% load static %}
{% load jalali %}
{% load humanize %}

{% block content %}

    <h1>بخش نوبت های دکتر</h1>
    <hr/>
    {% include "layouts/administration/includes/messages.html" %}
    {% if can_add_appointment %}
    <div class="text-center">
        <a class="btn btn-primary" href="{% url 'administration:add-user-appointment' user.id %}">افزودن نوبت
            <i class="fa fa-plus-square" aria-hidden="true"></i>
        </a>
    </div>
    <p></p>
    {% endif %}
    {% if appointments %}
    <div class="box">
        <div class="box-header">
          <h3 class="box-title">لیست نوبت ها</h3>

          <div class="box-tools">
            <p>مبلغ کل پرداخت شده ها : <span class="text-danger">{{sum|intcomma:False}}</span> <span class="text-info">تومان</span></p>

          </div>
        </div>
        <!-- /.box-header -->
        <div class="box-body table-responsive no-padding">
            <table class="table table-hover">
                <tbody>
                    <tr>
                        <th>شماره تلفن کاربر مربوطه</th>
                        <th>مبلغ پرداختی</th>
                        <th>پرداخت شده</th>
                        <th>استفاده شده</th>
                        <th>تاریخ ثبت</th>
                        <th>دستورات</th>
                    </tr>
                    {% for appointment in appointments %}
                    <tr>
                        <td>
                            {{appointment.user.phone_number}}
                        </td>
                        <td>
                            {% if appointment.paid_cost %}
                            <p class="text-success">{{appointment.paid_cost|intcomma:False}}</p>
                            {% else %}
                            <p class="text-danger">از طرف ادمین اضافه شده است</p>
                            {% endif %}
                        </td>
                        <td>
                            {% if appointment.is_paid %}
                            <p class="text-success">
                                <i class="fa fa-check-square" aria-hidden="true"></i>
                            </p>
                            {% else %} 
                            <p class="text-danger">
                                <i class="fa fa-window-close" aria-hidden="true"></i>
                            </p>
                            {% endif %}
                        </td>
                        <td>
                            {% if appointment.used %}
                            <p class="text-success">
                                <i class="fa fa-check-square" aria-hidden="true"></i>
                            </p>
                            {% else %} 
                            <p class="text-danger">
                                <i class="fa fa-window-close" aria-hidden="true"></i>
                            </p>
                            {% endif %}
                        </td>
                        <td>
                           {{appointment.created_at|tojalali}}
                        </td>
                        <td>
                            {% if can_edit_appointment %}
                            <a class="btn btn-{% if appointment.used %}danger{% else %}success{% endif %}" href="{% url 'administration:edit-doctor-appointment' appointment.id %}" title="تغییر به عنوان استفاده شده/نشده">
                                {% if appointment.used %}
                                    <i class="fa fa-window-close" aria-hidden="true"></i>
                                {% else %}
                                    <i class="fa fa-check-square" aria-hidden="true"></i>
                                {% endif %}
                            </a>
                        {% endif %}
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
      </div>
    {% else %}
    <div class="alert alert-warning">نوبتی وجود ندارد
        <i class="fa fa-exclamation-triangle" aria-hidden="true"></i>
    </div>
    {% endif %}

{% endblock %}